### ISSUE TITLE
Problem with dependency injection in version 1.7

### ISSUE THREAD

**Issue by centigrade-thomas-becker** [NAYZO/NzoUrlEncryptorBundle#10]
There is a problem with the latest release 1.7. After updating form 1.6 to 1.7 and starting the symfony console I get the following error:

```
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
"'Nzo\\UrlEncryptorBundle\\Annotations\\AnnotationResolver
        '" is not a valid class name for the "nzo.annotation_resolver" service.
```

The problem is an invalid line break before the closing `</parameter>` in `Resources/config/services.xml`:

```
 <parameters>
    <parameter key="nzo_url_encryptor.class">Nzo\UrlEncryptorBundle\UrlEncryptor\UrlEncryptor</parameter>
    <parameter key="encryptor_extension.class">Nzo\UrlEncryptorBundle\Twig\UrlEncryptorExtension</parameter>
    <parameter key="encryptor_annotation_resolver.class">Nzo\UrlEncryptorBundle\Annotations\AnnotationResolver
    </parameter>
</parameters>
```

Introduced in [this commit](https://github.com/NAYZO/NzoUrlEncryptorBundle/commit/9221776d22556c83d2d1c38bdeb29ed2f8041246#diff-1c64574ff1f633f0df3aac6fa7a25c7b)

**Comment by NAYZO** [comment]
:+1: 
Fixed: https://github.com/NAYZO/NzoUrlEncryptorBundle/pull/11
It's weird though, this bug is introduced by my IDE code formatting !!
