### ISSUE TITLE
Unexpected behaviour: Default value overwrites any value passed as parameter in the URL

### ISSUE THREAD

**Issue by maxdmg** [NAYZO/NzoUrlEncryptorBundle#17]
Hi,

I got back on my project and tested the new version of your bundle, the one that fixed #13. I also saw you added this to the documentation: https://github.com/NAYZO/NzoUrlEncryptorBundle/commit/dcf5c5691392dbc70a530934fed64b20dde7cb63#diff-04c6e90faac2675aa89e2176d2eec7d8R126

I don't think this behaviour is expected by anyone. The default value should kick in only when no value was passed in the URL. Now, regardless of what I'm sending through the URL, I always get the default value, totally blocking the use of the bundle encryption. This could be easily achieved by initializing a variable at the beginning of the action. I think the default value should be used only if no value was passed in the URL. 

I'm gonna use it without annotations to skip this bug.

**Comment by NAYZO** [comment]
Fixed in https://github.com/NAYZO/NzoUrlEncryptorBundle/pull/18
