### ISSUE TITLE
Wrong encrypting - decrypting

### ISSUE THREAD

**Issue by ufik** [NAYZO/NzoUrlEncryptorBundle#2]
Hi I guess there is something wrong with encryptor, look at this output.

```php 
$unsubData = 'subscriberId=1&deliveryId=1';

echo $encrypted = $this->container->get('nzo_url_encryptor')->encrypt($unsubData);
echo $d = $this->container->get('nzo_url_encryptor')->decrypt($encrypted);
var_dump($d);
```

```
qFBUT-qQ9udnLEIf-9pLElsJfKT8OOLrRzx8A1Zr4ps
subscriberId=1&deliveryId=1
string 'subscriberId=1&deliveryId=1����' (length=31)
```

This sign `�` is underline (_). I found it out by parse_url().

**Comment by NAYZO** [comment]
I couldn't reproduce the error you mentioned, could you send me the encryption key used, so I can investigate in more details your case.

**Comment by NAYZO** [comment]
@ufik fixed, :+1:

**Comment by ufik** [comment]
Very cool, thank you :)
