### ISSUE TITLE
Function mcrypt_module_open() is deprecated

### ISSUE THREAD

**Issue by ufik** [NAYZO/NzoUrlEncryptorBundle#23]
mcrypt module is deprecated from PHP version 7.1 and will be removed in version 7.2. Necessary to rewrite this usage into openssl module.

**Comment by NAYZO** [comment]
@ufik I've done a major updates to completely remove mcrypt_* and replace it with the OpenSSL extension.
c.f: https://github.com/NAYZO/NzoUrlEncryptorBundle/releases/tag/4.0

Thank you for the comment and sorry for my late response.
