### ISSUE TITLE
Can we use upgrade from 2.1 to 4.1 

### ISSUE THREAD

**Issue by speeeeeed2006** [NAYZO/NzoUrlEncryptorBundle#28]
Hello, 
I just tried to upgrade from 2.1 to 4.1 to use openssl no error I use only secret key and no secret_iv and no cipher_algorithm
when I try to compare to decrypt or encrypt the result isn't the same between the two version is there a way or a configuration to the new version give the same result to the old one and the possibility to decrypt it. 
thank you
Maybe I didn't use the new one in the best way.

**Comment by NAYZO** [comment]
Hello,
For now the bundle is not yet compatible with the version 4 of symfony. It's however compatible with v2 and v3.
I'm working on the upgrade for the v4 of symfony.

**Comment by NAYZO** [comment]
Hello @speeeeeed2006 

`NzoUrlEncryptorBundle` is now compatible with version **V4** of Symfony, just do a:
`composer update nzo/url-encryptor-bundle`  to update to the new _V4.2.0_ tag.
You can follow the instructions in[ Readme](https://github.com/NAYZO/NzoUrlEncryptorBundle/blob/master/README.md).
