### ISSUE TITLE
Is it acceptable to reuse the symfony-secret as encryption-secret?

### ISSUE THREAD

**Issue by centigrade-thomas-becker** [NAYZO/NzoUrlEncryptorBundle#3]
For convenience I use the secret key from my Symfony project as encryption key. My configuration looks like this:

```
nzo_url_encryptor:
    secret: %secret%      # max length of 24 characters
```

Could this have any negative side effects?

**Comment by NAYZO** [comment]
Not at all, what you did is just right and have no negative side effects  :+1:

**Comment by centigrade-thomas-becker** [comment]
Thanks for the answer.
