### ISSUE TITLE
Decrypt a word crypted in 3.1 don't work 

### ISSUE THREAD

**Issue by speeeeeed2006** [NAYZO/NzoUrlEncryptorBundle#30]
I crypted a word in 3.1 and I update to 4.0 to test and I can't decrypt it and when I crypt a word in 4.0 I can't decrypt it in 3.1. I made something wrong probably but I just followed the instructions. But it dosn't work. 
Is there maybe a configuration to use with **secret_iv** **cipher_algorithm** to have it work with the old version ? 
Thanks

**Comment by NAYZO** [comment]
Make sure that you keep the same bundle configuration between the two versions and it should work.

**Comment by speeeeeed2006** [comment]
it was the case I just changed in config.yml : 
**nzo_url_encryptor**:
    **secret_key**: *************
i didn't use secret_iv and cipher_algorithm but not the same result.

**Comment by NAYZO** [comment]
If you change the **secret_key** value the "decryption" and the "encryption" result will change accordingly!
So make sure you have the same **secret_key** value, otherwise you to rollback by using the base value.

**Comment by speeeeeed2006** [comment]
it was the same value but the crypt result isn't the same.

**Comment by NAYZO** [comment]
I'm talking about all the configuration, not only the **secret_key**

**Comment by speeeeeed2006** [comment]
Just to know is it the variable **secret_key** in 4.0 the same to **secret** in 3.1 ? becuse if it was the case I didn't change it I just changed the name in config.yml.

**Comment by NAYZO** [comment]
I don't know what do you mean by **secret** as the bundle doesn't contain this variable anyware in the configuration.
