### ISSUE TITLE
Symfony 4.4 compatibility

### ISSUE THREAD

**Issue by Fabricio872** [nayzo/NzoUrlEncryptorBundle#39]
hello i have problems to make it work on symfony 4.4.
I am  trying to install version "^4.3" and it gives me error: Conclusion: remove twig/twig v3.0.3
is possible to make this working on twig 3?

**Comment by nayzo** [comment]
Fixed: https://github.com/nayzo/NzoUrlEncryptorBundle/releases/tag/v4.3.1
Thank you.
