### ISSUE TITLE
Attempted to call function "mcrypt_module_open" from namespace "Nzo\UrlEncryptorBundle\UrlEncryptor".

### ISSUE THREAD

**Issue by TaqiOfficial** [NAYZO/NzoUrlEncryptorBundle#4]
After the installation and defining settings in config file. I am getting this error.
```
nzo_url_encryptor:
    secret: !12334!      
```
```
Attempted to call function "mcrypt_module_open" from namespace "Nzo\UrlEncryptorBundle\UrlEncryptor".
```

**Comment by NAYZO** [comment]
Could you show me more details about the error, I found it very strange though.

**Comment by TaqiOfficial** [comment]
It's gives only the above error. No more details. I am using Symfony 2.8 ? Did you test it with 2.8 or 3?

**Comment by NAYZO** [comment]
it has been tested successfully with 2.3 and 2.7
but from the error I really doubt that this come from the bundle. I think the "mcrypt_module_open" function is not loaded ... in fact you need the "mcrypt" module for this to work:
http://php.net/manual/en/book.mcrypt.php

**Comment by TaqiOfficial** [comment]
Yeh, it works now, after enabling mycrypt library. thanks.

**Comment by NAYZO** [comment]
Great, you're welcome :+1:
