### ISSUE TITLE
Set up a security policy

### ISSUE THREAD

**Issue by Techbrunch** [nayzo/NzoUrlEncryptorBundle#40]
Hello @nayzo,

I would like to report a security issue with this library but no security policy was defined for the project.

Could you add one: https://github.com/nayzo/NzoUrlEncryptorBundle/security/policy

So that I can report the issue through the right channel.

I the meantime I would advise against using this library.

Thanks

**Comment by nayzo** [comment]
Hello @Techbrunch,

You can report the security  issue at: contact [@] alakhefifi [.] com
Thank you in advance.

**Comment by nayzo** [comment]
No security issue detected as far as using the bundle there is no way to decrypt the encrypted text without using the bundle it self !
From an encrypted text you cannot get the original text without using the bundle (which is the whole purpose of the bundle).
You may have found a glitch but it has no effect on the equation and it's mentioned above !
Thank you anyway.
Closing this issue.

**Comment by Techbrunch** [comment]
There are actually multiple critical issues with this library, if @nayzo does not contact me I'll make them public.

**Comment by nayzo** [comment]
Email sent, I see the problem with AES-CTR combination, I'll change it to AES-XTS.
Thanks @Techbrunch
