### ISSUE TITLE
Add information related to security in the Readme

### ISSUE THREAD

**Issue by Techbrunch** [nayzo/NzoUrlEncryptorBundle#41]
I suggest you add this to the README:

By default this library is using `aes-256-ctr`. 

CTR mode (without any additional authentication step) is malleable, which means that **it is possible to change the meaning of the ciphertext.**

Thus by default this library does not prevent users from modifying encrypted data.

**This library should not be used to encrypt sensitive data.**

**Since the key is reused, if a user is able to guess the plaintext of one ciphertext he will be able to decrypt any ciphertext**.

If this application is used to encrypt object ID it should not replace any additional control regarding rights since it is likely that the plaintext is guessable and that by default AES with CTR mode is malleable leading to [IDOR](https://portswigger.net/web-security/access-control/idor).

This library is only adding security through [obscurity](Security_through_obscurity).

---

For the record, before release 5.0.1, the key and iv where not mandatory which means that anyone  could have decrypted and modified the encrypted data.

**Comment by nayzo** [comment]
Done.
Thnaks @Techbrunch
