### ISSUE TITLE
Support for Symfony < 5 dropped in v4.3.2

### ISSUE THREAD

**Issue by ThomasRueckert** [nayzo/NzoUrlEncryptorBundle#42]
Hey @nayzo,

i am having problems with updating this bundle to version 4.3.2. I am using symfony version 4.4.

The documentation of this bundle says `This Version (^5.0) is compatible with Symfony >= 5, for Symfony 2, 3 and 4 use the composer tag: ^4.3 instead.`

However, from version [4.3.1](https://github.com/nayzo/NzoUrlEncryptorBundle/blob/v4.3.1/composer.json) to [4.3.2](https://github.com/nayzo/NzoUrlEncryptorBundle/blob/v4.3.2/composer.json) the support for symfony 4 and lower was dropped:

```
{
    //...
    "require": {
        //...
        "symfony/framework-bundle": "^5.0",
        //...
    },
    //...
}
```

I guess this was a mistake?

**Comment by nayzo** [comment]
Hello @ThomasRueckert,

Yes indeed it's a mistake, I'll fix that.
Thank you.

**Comment by ThomasRueckert** [comment]
Thanks for the quick reply!

**Comment by nayzo** [comment]
Hello,
v4.3.2 is Fixed.
Thank you @ThomasRueckert
