### ISSUE TITLE
Zend-eventmanager  is abandoned

### ISSUE THREAD

**Issue by juvabien** [nayzo/NzoUrlEncryptorBundle#45]
Hi,

Under Symfony 5.0.* composer alerts with this message : 

`Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.`

Any fix?

**Comment by nayzo** [comment]
Hello, Ok I'll check that.

**Comment by nayzo** [comment]
I don't use `zendframework/zend-eventmanager` in the bundle.
see: https://github.com/nayzo/NzoUrlEncryptorBundle/blob/master/composer.json#L16

**Comment by juvabien** [comment]
sorry and thank you ;)
