### ISSUE TITLE
Symfony 5 compatibility

### ISSUE THREAD

**Issue by hbocanegra** [nayzo/NzoUrlEncryptorBundle#47]
Hi, I tried to install the package on my project with SF 5 and got the problem shown in the image. Can you help me please?
![fail sf5](https://user-images.githubusercontent.com/1136240/90124628-009bd400-dd61-11ea-99e0-d39cf12c79d2.png)

**Comment by nayzo** [comment]
Hello,

You just need to configure the mandatory "secret_key" parameter as mentioned in the screen ouput.
See: https://github.com/nayzo/NzoUrlEncryptorBundle#configure-your-applications-configyml
