### ISSUE TITLE
Encrypted strings with 5.0.0 not working with 6.0.0 anymore

### ISSUE THREAD

**Issue by leik-software** [nayzo/NzoUrlEncryptorBundle#49]
I have encrypted strings in database and updated the package. After that I could not decrypt the strings anymore so I had to go back to v5.0.0 again. What I'm supposed to do when update to v6?

**Comment by nayzo** [comment]
v6 is a major release !
You need to re-encrypt your data with the new release in order for you to make the upgarde.
There is no straightforward migration if you have data encrypted with the 5.0.0 version. So decrypt the data with 5.0.0 and encrypt it again after upgrade to v6.
