### ISSUE TITLE
PHP 8 attributes not working

### ISSUE THREAD

**Issue by FluffyDiscord** [nayzo/NzoUrlEncryptorBundle#52]
You can't add ParamDecryptor as attribute in PHP8

![obrazek](https://user-images.githubusercontent.com/10332247/156528581-1f4a8836-2851-4128-b499-f8986199bf9c.png)

to fix it you have to add the official attribute

```php
/**
 * @Annotation
 */
#[\Attribute(\Attribute::TARGET_METHOD)] // <-- this here
class ParamDecryptor
{
    public $params;
}

```

**Comment by nayzo** [comment]
Not True !
It works fine, it has been tested on PHP 8.0 and PHP 8.1
Example:
`
//...
use Nzo\UrlEncryptorBundle\Annotations\ParamEncryptor;
use Nzo\UrlEncryptorBundle\Encryptor\Encryptor;

class TestController extends AbstractController
{
    private $encryptor;

    public function __construct(Encryptor $encryptor)
    {
        $this->encryptor = $encryptor;
    }

#[Route('/test/{id}', name: 'app_test')]
    #[ParamEncryptor(["id"])]
    public function index(string $id): Response
    {

        $decrypted = $this->encryptor->decrypt($id);

        dd($id, $decrypted);

       //...
    }`

**Comment by WebDevM4DC** [comment]
> Not True ! It works fine, it has been tested on PHP 8.0 and PHP 8.1 Example:
> 
> ```
> //...
> use Nzo\UrlEncryptorBundle\Annotations\ParamEncryptor;
> use Nzo\UrlEncryptorBundle\Encryptor\Encryptor;
> 
> class TestController extends AbstractController
> {
>     private $encryptor;
> 
>     public function __construct(Encryptor $encryptor)
>     {
>         $this->encryptor = $encryptor;
>     }
> 
>     #[Route('/test/{id}', name: 'app_test')]
>     #[ParamEncryptor(["id"])]
>     public function index(string $id): Response
>     {
> 
>         $decrypted = $this->encryptor->decrypt($id);
> 
>         dd($id, $decrypted);
> 
>        //...
>     }
> ```

Why do you inject the encryptor since you state here: https://github.com/nayzo/NzoUrlEncryptorBundle#in-the-controller-with-annotation-service that with annotations it's not needed?

Also, I did a simple test with annotations and I can pass any string to the URL parameter... no error or anything.

**Comment by hanishsingla** [comment]
> Not True ! It works fine, it has been tested on PHP 8.0 and PHP 8.1 Example:
> 
> ```
> //...
> use Nzo\UrlEncryptorBundle\Annotations\ParamEncryptor;
> use Nzo\UrlEncryptorBundle\Encryptor\Encryptor;
> 
> class TestController extends AbstractController
> {
>     private $encryptor;
> 
>     public function __construct(Encryptor $encryptor)
>     {
>         $this->encryptor = $encryptor;
>     }
> 
>     #[Route('/test/{id}', name: 'app_test')]
>     #[ParamEncryptor(["id"])]
>     public function index(string $id): Response
>     {
> 
>         $decrypted = $this->encryptor->decrypt($id);
> 
>         dd($id, $decrypted);
> 
>        //...
>     }
> ```

@WebDevM4DC, can you help me also to understand this example?

To me, it seems `#[ParamEncryptor(["id"])]` is not doing anything at all in this example. Otherwise, there would be no need of `$decrypted = $this->encryptor->decrypt($id);`

It was working fine with Symfony 6.1 and PHP 8.1, but with Symfony 6.2, it throws this error `'Attempting to use non-attribute class "Nzo\UrlEncryptorBundle\Annotations\ParamDecryptor" as attribute'`

**Comment by WebDevM4DC** [comment]
> #[Route('/test/{id}', name: 'app_test')]
>     #[ParamEncryptor(["id"])]

Because of these attributes:

```
#[Route('/test/{id}', name: 'app_test')]
#[ParamEncryptor(["id"])]
```

There is no need to call decrypt as it gets decrypted automatically. It works very well and we are already using it in production.

**Comment by hanishsingla** [comment]
@WebDevM4DC, with Symfony 6.2 ?

**Comment by nayzo** [comment]
Fixed: https://github.com/nayzo/NzoUrlEncryptorBundle/releases/tag/v6.2.5
thanks.
