### ISSUE TITLE
Does not work with invokable controllers

### ISSUE THREAD

**Issue by benr77** [nayzo/NzoUrlEncryptorBundle#58]
I have discovered that the bundle does not work with invokable controller classes. https://symfony.com/doc/current/controller/service.html#invokable-controllers

The problem is that in `AnnotationResolver` you are expecting `$event->getController()` to return an array, whereas with you use `__invoke()` for the controller method name, `$event->getController()` actually returns the controller directly instead of it being wrapped in an array.

https://github.com/nayzo/NzoUrlEncryptorBundle/blob/6bf6cf9aaa2826021ee3b12d0443cc27e3bc5f3f/Annotations/AnnotationResolver.php#L31

I will submit a PR in a moment

**Comment by nayzo** [comment]
Thank you for the issue.
Fixed in: https://github.com/nayzo/NzoUrlEncryptorBundle/commit/4a9ca1c0fa94526e587a86db03218f9c71e83945
