### ISSUE TITLE
Error: Attempting to use non-attribute class in Symfony 6.2

### ISSUE THREAD

**Issue by hanishsingla** [nayzo/NzoUrlEncryptorBundle#60]
In symfony 6.2 (symfony/http-kernel v6.2), this [commit](https://github.com/symfony/http-kernel/commit/7b67334f1022f383322332f8b2123ae7cdcc22d6) has altered how attributes are parsed.

After updating to Symfony 6.2, this error is displayed on any route using "ParamDecryptor" attribute

`Error: Attempting to use non-attribute class "Nzo\UrlEncryptorBundle\Annotations\ParamDecryptor" as attribute`

After adding #[\Attribute] to ParamDecryptor class, error is changed to following

`Error: Attribute class Nzo\UrlEncryptorBundle\Annotations\ParamDecryptor does not have a constructor, cannot pass arguments`

Updating Nzo\UrlEncryptorBundle\Annotations\ParamDecryptor class like the following, fixes these errors

```
/**
 * @Annotation
 */
#[\Attribute]
class ParamDecryptor
{
    public function __construct(public $params=[]){

    }
}
```

**Comment by nayzo** [comment]
Fixed: https://github.com/nayzo/NzoUrlEncryptorBundle/releases/tag/v6.2.5
thanks.
