### ISSUE TITLE
ParamDecryptor constructor does not accept parameter as stated in docs

### ISSUE THREAD

**Issue by FluffyDiscord** [nayzo/NzoUrlEncryptorBundle#63]
The following example using attribute is confusing, since it works, but only because you magically take it's arguments in your processor
```php
  /**
    * @ParamDecryptor({"id", "foo"})   OR    #[ParamDecryptor(["id", "foo"])]
    */
```
The signature of ParamDecryptor's constructor does not accept any parameter, resulting in confused PhpStorm and any other IDE
![image](https://github.com/nayzo/NzoUrlEncryptorBundle/assets/10332247/2674eb90-ed24-4585-b43f-042bc5d21093)

Please make the ParamEncryptor accept array in constructor.

**Comment by nayzo** [comment]
Fixed in https://github.com/nayzo/NzoUrlEncryptorBundle/releases/tag/v6.2.7

Thank you.
