### ISSUE TITLE
Hello I got an issue resolving the parameter

### ISSUE THREAD

**Issue by Fabricio872** [nayzo/NzoUrlEncryptorBundle#65]
Hello I am getting an error on Symfony 6.3 trying to decrypt the parameter defined as Annotations
```
Symfony\Component\HttpFoundation\ParameterBag::has(): Argument #1 ($key) must be of type string, array given, called in 
/srv/app/vendor/nzo/url-encryptor-bundle/Annotations/AnnotationResolver.php on line 71
```
Are annotations completely discontinued or is this an unexpected issue? I have found the solution to the issue which appears to work with both annotations and attributes but I have done only a simple testing for it. I will create PR for it.

**Comment by nayzo** [comment]
Yes, you're using an old config i guess. no need for "params=". It should be like this (more simpler):


```php
   /**
    * @ParamDecryptor({"id", "foo"})   OR    #[ParamDecryptor(["id", "foo"])]
    */

   /**
    * @ParamEncryptor({"id", "foo"})   OR    #[ParamEncryptor(["id", "foo"])]
    */
``` 

See the documentation in the Readme.md page.

**Comment by Fabricio872** [comment]
Thank you perfect this is defenetly nicer
