### ISSUE TITLE
ParamDecryptor requires PHP 7.4 for typed properties

### ISSUE THREAD

**Issue by rctgamer3** [nayzo/NzoUrlEncryptorBundle#68]
Version 6.2.7 still has a PHP version requirement of only >=7.1.3. However, due to the refactor done in 77996833705c4e5b8294a890a4c3719cd5d679cf
files such as ParamDecryptor now use PHP 7.4's typed properties, causing issues on applications below 7.4.

**Comment by nayzo** [comment]
Thank you @rctgamer3 
Fixed: https://github.com/nayzo/NzoUrlEncryptorBundle/releases/tag/v6.2.8
