### ISSUE TITLE
Remove dependency on doctrine/annotations

### ISSUE THREAD

**Issue by dubbs** [nayzo/NzoUrlEncryptorBundle#69]
Doctrine is moving away from annotations: https://www.doctrine-project.org/2022/11/04/annotations-to-attributes.html

Also, the doctrine orm project is deprecating the annotations driver: https://www.doctrine-project.org/projects/doctrine-orm/en/2.16/reference/annotations-reference.html

Consider moving away from doctrine/annotations and only providing support for attributes.

Note: This would probably also require adjusting the php version in the composer.json file.

**Comment by nayzo** [comment]
I intentionally keep `doctrine/annotations` (at least for now) to continue supporting older versions of Symfony where `doctrine/annotations` is still in use.
PS: `doctrine/annotations` has been removed in Symfony 6 but is still used in Symfony 5 and lower. I know it's not mandatory, but not everyone is using Attributes (PHP 8).

**Comment by dubbs** [comment]
Thanks for letting me know!  No rush on this, its more of a nice to have.

**Comment by nayzo** [comment]
Thank you :)
