### ISSUE TITLE
Symfony 7 compatibility

### ISSUE THREAD

**Issue by hanishsingla** [nayzo/NzoUrlEncryptorBundle#70]
Symfony7 requires minimum PHP 8.2.0 and `Doctrine\Common\Annotations\Reader` has been deprecated due to PHP8 attributes https://www.doctrine-project.org/projects/doctrine-annotations/en/2.0/index.html#deprecation-notice

Due to this this bundle can't use annotations reader anymore and has started to throw this error in new Symfony7

`The service "nzo.annotation_resolver" has a dependency on a non-existent service "annotations.reader". Did you mean this: "translation.reader"?`

I hope there is some solution to this issue keeping BC in mind

**Comment by nayzo** [comment]
Done.
cf: https://github.com/nayzo/NzoUrlEncryptorBundle/releases/tag/v6.3.0

Thank you!
