### ISSUE TITLE
Deprecated Twig-class

### ISSUE THREAD

**Issue by centigrade-thomas-becker** [NAYZO/NzoUrlEncryptorBundle#8]
The current version 1.6 uses a Twig-class that is marked as deprecated. 

In order to upgrade my project from Symfony 2.6 to 3.0 I searched the code (including the vendor bundles) for deprecation warnings. I found such a class in `Twig/UrlEncryptorExtension.php`:

```
public function getFilters()
{
    return array(
        'urlencrypt' => new \Twig_Filter_Method($this, 'urlencryptFilter'),
        'urldecrypt' => new \Twig_Filter_Method($this, 'urldecryptFilter'),
    );
}
```

According to the [Twig documentation](http://twig.sensiolabs.org/doc/deprecated.html#filters) The class `Twig_Filter_Method` is deprecated and will be removed in Twig 2.0:

> As of Twig 1.x, use Twig_SimpleFilter to add a filter. The following classes and interfaces will be removed in 2.0:
>- Twig_FilterInterface
>- Twig_FilterCallableInterface
>- Twig_Filter
>- Twig_Filter_Function
>- Twig_Filter_Method
>
> As of Twig 2.x, the Twig_SimpleFilter class is deprecated and will be removed in Twig 3.x (use Twig_Filter instead). In Twig 2.x, Twig_SimpleFilter is just an alias for Twig_Filter.

Is somebody already working on this, or should I submit a patch myself?

**Comment by NAYZO** [comment]
Nice catch thanks :+1: 
Fixed, see:  https://github.com/NAYZO/NzoUrlEncryptorBundle/pull/9
